import requests

# Your IndexNow API key
api_key = "a1c6c1adea464604b4fe9cc1fda70d04"

# Create a list of URLs
urls = [
    "https://www.pixacura.com/tangem-and-visa-revolutionize-crypto-payments",
"https://www.pixacura.com/small-businesses-blockchain-payments",
"https://www.pixacura.com/manipulate-crypto-markets",
"https://www.pixacura.com/bitcoin-to-zero",
"https://www.pixacura.com/who-is-ripple-and-what-is-xrp",
"https://www.pixacura.com/investing-the-importance-of-use-cases",
"https://www.pixacura.com/stronghold-shx",
"https://www.pixacura.com/a-look-into-mx-linux",
"https://www.pixacura.com/what-is-crypto",
"https://www.pixacura.com/why-learn-python",
"https://www.pixacura.com/dollar-cost-averaging-is-a-smart-strategy-for-small-crypto-investors",
"https://www.pixacura.com/bpm-wallet",
"https://www.pixacura.com/the-erosion-of-democracy",
"https://www.pixacura.com/popular-open-source-software",
"https://www.pixacura.com/what-is-ai",
"https://www.pixacura.com/ai-images-with-craiyon",
"https://www.pixacura.com/eating-healthy-on-a-budget",
"https://www.pixacura.com/bitcoin-etf-now-live",
"https://www.pixacura.com/thyme-health-benefits",
"https://www.pixacura.com/ripple-partners-with-uphold",
"https://www.pixacura.com/blackdot-revolutionizing-the-tattoo-industry",
"https://www.pixacura.com/amazon-invests-4-billion-in-ai-technology",
"https://www.pixacura.com/xrp-investment",
"https://www.pixacura.com/electric-vehicles-may-not-be-what-they-re-claiming",
"https://www.pixacura.com/embracing-c-let-s-take-a-look",
"https://www.pixacura.com/the-uk-crypto-scene-a-growing-hub-for-innovation",
"https://www.pixacura.com/axiom-space-building-the-future-of-space-exploration",
"https://www.pixacura.com/bard-for-business",
"https://www.pixacura.com/brics-expands-to-include-6-new-members",
"https://www.pixacura.com/the-health-benefits-and-history-of-liquorice",
"https://www.pixacura.com/unveiling-the-wonders-of-cumin-a-journey-into-history-and-health",
"https://www.pixacura.com/the-health-benefits-of-cinnamon",
"https://www.pixacura.com/the-real-benefits-of-honey",
"https://www.pixacura.com/ripple-applies-for-fca-registration",
"https://www.pixacura.com/the-hopeful-message-of-star-trek",
"https://www.pixacura.com/digital-tokens-the-next-big-thing-for-businesses",
"https://www.pixacura.com/how-to-network",
"https://www.pixacura.com/banking-has-changed",
"https://www.pixacura.com/how-to-bake-cupcakes-as-a-beginner",
"https://www.pixacura.com/why-hasn-t-xrp-pumped",
"https://www.pixacura.com/how-to-get-a-good-night-s-sleep",
"https://www.pixacura.com/ripple-scores-major-victory-in-sec-lawsuit-xrp-soars",
"https://www.pixacura.com/top-10-plants-for-gardening-beginners",
"https://www.pixacura.com/gardening",
"https://www.pixacura.com/5-ways-to-boost-your-immunity",
"https://www.pixacura.com/the-dangers-of-stress",
"https://www.pixacura.com/how-john-grew-his-small-business-with-fiverr",
"https://www.pixacura.com/70s-and-80s",
"https://www.pixacura.com/small-businesses-crypto-invest",
"https://www.pixacura.com/how-to-create-a-strong-brand-identity-for-your-small-business",
"https://www.pixacura.com/exploring-altcoins",
"https://www.pixacura.com/10-signs-you-need-to-see-a-doctor",
"https://www.pixacura.com/google-office-tools",
"https://www.pixacura.com/the-dire-state-of-uk-dental-care",
"https://www.pixacura.com/king-charles-crypto",
"https://www.pixacura.com/bank-of-england-in-trouble",
"https://www.pixacura.com/bard-and-how-to-use-it",
"https://www.pixacura.com/xrp-the-future-looks-bright",
"https://www.pixacura.com/could-bitcoin-go-down-never-to-recover",
"https://www.pixacura.com/xrp-xdc-xlm-the-trinity",
"https://www.pixacura.com/photos-on-a-budget",
"https://www.pixacura.com/small-business-in-a-recession",
"https://www.pixacura.com/motivation-as-a-business-owner",
"https://www.pixacura.com/removing-your-crypto-from-exchanges",
"https://www.pixacura.com/tomorrows-world-look-back",
"https://www.pixacura.com/alright-here-s-a-lighthearted-take-on-the-tips-today-i-m-h",
"https://www.pixacura.com/bill-hinman-emails-released",
"https://www.pixacura.com/not-following-business-trends-can-benefit-your-company",
"https://www.pixacura.com/embracing-work-life-balance",
"https://www.pixacura.com/unleashing-the-power-of-robots-shaping-a-bright-future",
"https://www.pixacura.com/revitalise-your-life-unleashing-the-extraordinary-benefits-of-regular-exercise",
"https://www.pixacura.com/smart-tips-for-saving-money-and-building-wealth",
"https://www.pixacura.com/six-best-card-wallets",
"https://www.pixacura.com/5g-technology-what-you-need-to-know",
"https://www.pixacura.com/marketing-strategies-for-your-home-based-business-on-a-limited-budget",
"https://www.pixacura.com/setting-up-a-productive-home-office-for-your-small-business",
"https://www.pixacura.com/the-benefits-of-starting-a-home-based-business",
"https://www.pixacura.com/what-is-the-debt-ceiling-and-why-is-it-important",
"https://www.pixacura.com/xumm-wallet-to-rebrand-as-xaman",
"https://www.pixacura.com/xrai-glass-empowering-deaf-and-hard-of-hearing-individuals-with-augmented-reality",
"https://www.pixacura.com/a-beginner-s-guide-how-to-get-involved-in-crypto",
"https://www.pixacura.com/restoring-public-trust-the-key-to-banking-success-and-transformation",
"https://www.pixacura.com/understanding-central-bank-digital-currency-cbdc-is-this-the-future-of-money",
"https://www.pixacura.com/scotland-s-scenic-masterpieces-the-top-10-golf-courses-amidst-nature-s-embrace",
"https://www.pixacura.com/guerrilla-marketing-for-small-business",
"https://www.pixacura.com/the-importance-of-having-a-website",
"https://www.pixacura.com/parents-and-the-importance-of-prioritizing-each-other-nurturing-your-relationship",
"https://www.pixacura.com/becoming-new-parents-the-nerves-sleepless-nights-and-the-sheer-joy-of-a-baby-s-laughter",
"https://www.pixacura.com/don-t-discard-your-old-laptop-embrace-linux-in-today-s-fast",
"https://www.pixacura.com/xinfin-xdc-the-benefits-for-business-and-investment",
"https://www.pixacura.com/starting-a-small-home-based-business-the-pros-cons-and-benefits",
"https://www.pixacura.com/ripple-and-the-us-sec-a-legal-battle-for-the-future-of-crypto",
"https://www.pixacura.com/autosave-647423f6981dd4c3d75861482a4d33da",
"https://www.pixacura.com/e-bikes-unleashing-the-power",
"https://www.pixacura.com/the-need-and-requirements-for-a-cookie-banner-on-a-website",
"https://www.pixacura.com/the-power-of-gratitude-in-daily-life",
"https://www.pixacura.com/all-work-and-no-play-makes-jack-a-burn-out",
"https://www.pixacura.com/a-little-red-wine-never-hurt-anyone-did-it",
"https://www.pixacura.com/walk-a-mile-a-day-and-you-ll-notice-the-difference",
"https://www.pixacura.com/what-is-hummus-and-is-it-good-for-you",
"https://www.pixacura.com/revolut-a-bank-worth-considering",
"https://www.pixacura.com/finance-budgeting-and-your-home",
"https://www.pixacura.com/i-tried-the-uphold-card-and-wow",
"https://www.pixacura.com/china-s-economy-has-been-one-of-the-fastest-growing-in-the-w",
"https://www.pixacura.com/geany-a-great-all-round-ide",
"https://www.pixacura.com/in-today-s-digital-age-visual-content-is-important",
"https://www.pixacura.com/small-business-accepting-crypto",
"https://www.pixacura.com/logos-and-branding-why-they-matter-for-your-business",
"https://www.pixacura.com/the-benefits-of-using-bludit-cms-for-your-website",
"https://www.pixacura.com/xiaomi-12-lite-a-budget-friendly-phone-with-impressive-features",
"https://www.pixacura.com/economic-crash-coming",
"https://www.pixacura.com/tesco-is-this-a-good-investment-opportunity",
"https://www.pixacura.com/category-list",
"https://www.pixacura.com/a-closer-look-at-linux",
"https://www.pixacura.com/why-add-coinbase-crypto-button-to-your-website",
"https://www.pixacura.com/crypto-coffee",
"https://www.pixacura.com/search",
"https://www.pixacura.com/a-true-photoshop-alternative",
"https://www.pixacura.com/cookie-policy",
"https://www.pixacura.com/site-terms",
"https://www.pixacura.com/contact",
"https://www.pixacura.com/about"
]

# IndexNow endpoint (using Bing as an example)
indexnow_url = f"https://www.bing.com/indexnow?key={api_key}"

# Submit each URL to IndexNow
for url in urls:
    params = {
        "url": url,
        "key": api_key
    }
    
    response = requests.get(indexnow_url, params=params)
    print(f"Submitted {url} - Status: {response.status_code}, Response: {response.text}")